### PR TITLE
Hail mary for TPC alert problem

### PR DESCRIPTION
**Pull request by cguardia**

### CODE REVIEW

**Comment by tseaver** [comment]
I'm presuming that you don't know how the transaction is getting into that state (I couldn't figure it out, either, when Paul asked me to look).  I would assume that skipping the `on_abort` call might be the Right Thing(TM) in such a case.

**Comment by cguardia** [comment]
Yeah, I couldn't figure it out. I will revisit this at some point, but I'm trying to save Paul from the avalanche of alerts. Updated the PR based on your comment.

**Comment by pauleveritt** [comment]
I will do a merge and likely do a release today, as it is a holiday at OSF.

**Comment by pauleveritt** [comment]
I hand-edited this change in production, to avoid restarting the universe and losing the cache. Since it is deployed, I might as well merge it. :)

**Pull request merged**
